-------------TABLE POSITION ---------------
CREATE TABLe Position(
 Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
 NamePosition NVARCHAR(max) NOT NULL,
);

-------------TABLE USERTYPE-----------------
CREATE TABLE UserType(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Type NVARCHAR(MAX) NOT NULL
);
-------------TABLE USER -------------------
CREATE TABLE Users (
  Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  Name NVARCHAR(MAX) NOT NULL,
  LastName NVARCHAR (MAX) NOT NULL,
  Email NVARCHAR (MAX) NOT NULL,
  Password NVARCHAR (MAX) NOT NULL,
  IdPosition UNIQUEIDENTIFIER NOT NULL,
  IdUserType UNIQUEIDENTIFIER NOT NULL	
);
 --------------TABLE COMPANY----------------
	CREATE TABLE Company (
	  Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	  Name NVARCHAR(MAX) NOT NULL,
	  Email NVARCHAR(MAX) NOT NULL
	);
	 -------------TABLE PROJECT -----------------
	CREATE TABLE Project(
	 Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	 Name NVARCHAR(MAX)NOT NULL,
	  StartDate DATE NOT NULL,
	  DeliveryDate DATE NOT NULL,
	  TotalAmount DECIMAL NOT NULL,
	  IdCompany UNIQUEIDENTIFIER NOT NULL
	);

	CREATE TABLE UsersOnProject(
	  Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	  IdUser UNIQUEIDENTIFIER NOT NULL,
	  IdProject UNIQUEIDENTIFIER NOT NULL
	);
	--------------TABLE PRIORITY ----------------
	CREATE TABLE Priority(
	  Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	  Name NVARCHAR NOT NULL,
	);


	--------------TABLE TASK---------------------
	CREATE TABLE Task(
	  Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	  Description NVARCHAR(MAX) NOT NULL,
	  StartDate DATE NOT NULL,
	  DeliveryDate DATE NOT NULL,
	  State NVARCHAR(MAX) NOT NULL,
	  Amount DECIMAL NOT NULL,
	  IdUserAssigned UNIQUEIDENTIFIER NOT NULL,
	  IdPriority UNIQUEIDENTIFIER NOT NULL,
	  IdProject UNIQUEIDENTIFIER NOT NULL
	);

	--------------ADD FOREIGN KEY CONSTRAINT---------

	ALTER TABLE Users ADD CONSTRAINT FK_PositionUser FOREIGN KEY (IdPosition) REFERENCES Position(Id);
	ALTER TABLE Users ADD CONSTRAINT FK_UserTypeUser FOREIGN KEY (IdUserType) REFERENCES UserType(Id);
	ALTER TABLE Project ADD CONSTRAINT FK_CompanyProject FOREIGN KEY(IdCompany) REFERENCES Company(Id);
	ALTER TABLE UsersOnProject ADD CONSTRAINT FK_UsersInProject  FOREIGN KEY(IdUser) REFERENCES Users(Id);
	ALTER TABLE UsersOnProject ADD CONSTRAINT FK_ProjectUserProject  FOREIGN KEY(IdProject) REFERENCES Project(Id);
	ALTER TABLE Task  ADD CONSTRAINT FK_TaskUserAssigned FOREIGN KEY(IdUserAssigned)REFERENCES Users(Id);
	ALTER TABLE Task  ADD CONSTRAINT Fk_PriorityTask FOREIGN KEY (IdPriority) REFERENCES Priority(Id);
	ALTER TABLE Task ADD CONSTRAINT FK_ProjectTask  FOREIGN KEY  (IdProject) REFERENCES Project (Id);
	ALTER TABLE Project ADD State VARCHAR(200) DEFAULT 'A'
    ALTER TABLE Company ADD State VARCHAR(200) DEFAULT 'A'


